var countriesIn = function(code, full) {
  var areIn = CONTINENTS.reduce(function(m, e, i, arr) {
        if (e[1] == code) {
          m.push(e[0]);
        }
        return m;
      }, []);
  if (full) {
    return COUNTRIES.reduce(function(m, e, i, arr) {
      if (areIn.indexOf(e[1]) != -1) {
        m.push(e[0]);
      }
      return m;
    }, []);
  } else {
    return areIn;
  }
};

var COUNTRIES = [
["Afghanistan", "AF"],
["Åland Islands", "AX"],
["Albania", "AL"],
["Algeria", "DZ"],
["American Samoa", "AS"],
["Andorra", "AD"],
["Angola", "AO"],
["Anguilla", "AI"],
["Antarctica", "AQ"],
["Antigua and Barbuda", "AG"],
["Argentina", "AR"],
["Armenia", "AM"],
["Aruba", "AW"],
["Australia", "AU"],
["Austria", "AT"],
["Azerbaijan", "AZ"],
["Bahamas", "BS"],
["Bahrain", "BH"],
["Bangladesh", "BD"],
["Barbados", "BB"],
["Belarus", "BY"],
["Belgium", "BE"],
["Belize", "BZ"],
["Benin", "BJ"],
["Bermuda", "BM"],
["Bhutan", "BT"],
["Bolivia (Plurinational State of)", "BO"],
["Bonaire", "Sint Eustatius and Saba", "BQ"],
["Bosnia and Herzegovina", "BA"],
["Botswana", "BW"],
["Bouvet Island", "BV"],
["Brazil", "BR"],
["British Indian Ocean Territory", "IO"],
["Brunei Darussalam", "BN"],
["Bulgaria", "BG"],
["Burkina Faso", "BF"],
["Burundi", "BI"],
["Cambodia", "KH"],
["Cameroon", "CM"],
["Canada", "CA"],
["Cabo Verde", "CV"],
["Cayman Islands", "KY"],
["Central African Republic", "CF"],
["Chad", "TD"],
["Chile", "CL"],
["China", "CN"],
["Christmas Island", "CX"],
["Cocos (Keeling) Islands", "CC"],
["Colombia", "CO"],
["Comoros", "KM"],
["Congo", "CG"],
["Congo (Democratic Republic of the)", "CD"],
["Cook Islands", "CK"],
["Costa Rica", "CR"],
["Côte d'Ivoire", "CI"],
["Croatia", "HR"],
["Cuba", "CU"],
["Curaçao", "CW"],
["Cyprus", "CY"],
["Czech Republic", "CZ"],
["Denmark", "DK"],
["Djibouti", "DJ"],
["Dominica", "DM"],
["Dominican Republic", "DO"],
["Ecuador", "EC"],
["Egypt", "EG"],
["El Salvador", "SV"],
["Equatorial Guinea", "GQ"],
["Eritrea", "ER"],
["Estonia", "EE"],
["Ethiopia", "ET"],
["Falkland Islands (Malvinas)", "FK"],
["Faroe Islands", "FO"],
["Fiji", "FJ"],
["Finland", "FI"],
["France", "FR"],
["French Guiana", "GF"],
["French Polynesia", "PF"],
["French Southern Territories", "TF"],
["Gabon", "GA"],
["Gambia", "GM"],
["Georgia", "GE"],
["Germany", "DE"],
["Ghana", "GH"],
["Gibraltar", "GI"],
["Greece", "GR"],
["Greenland", "GL"],
["Grenada", "GD"],
["Guadeloupe", "GP"],
["Guam", "GU"],
["Guatemala", "GT"],
["Guernsey", "GG"],
["Guinea", "GN"],
["Guinea-Bissau", "GW"],
["Guyana", "GY"],
["Haiti", "HT"],
["Heard Island and McDonald Islands", "HM"],
["Holy See", "VA"],
["Honduras", "HN"],
["Hong Kong", "HK"],
["Hungary", "HU"],
["Iceland", "IS"],
["India", "IN"],
["Indonesia", "ID"],
["Iran (Islamic Republic of)", "IR"],
["Iraq", "IQ"],
["Ireland", "IE"],
["Isle of Man", "IM"],
["Israel", "IL"],
["Italy", "IT"],
["Jamaica", "JM"],
["Japan", "JP"],
["Jersey", "JE"],
["Jordan", "JO"],
["Kazakhstan", "KZ"],
["Kenya", "KE"],
["Kiribati", "KI"],
["Korea (Democratic People's Republic of)", "KP"],
["Korea (Republic of)", "KR"],
["Kuwait", "KW"],
["Kyrgyzstan", "KG"],
["Lao People's Democratic Republic", "LA"],
["Latvia", "LV"],
["Lebanon", "LB"],
["Lesotho", "LS"],
["Liberia", "LR"],
["Libya", "LY"],
["Liechtenstein", "LI"],
["Lithuania", "LT"],
["Luxembourg", "LU"],
["Macao", "MO"],
["Macedonia (the former Yugoslav Republic of)", "MK"],
["Madagascar", "MG"],
["Malawi", "MW"],
["Malaysia", "MY"],
["Maldives", "MV"],
["Mali", "ML"],
["Malta", "MT"],
["Marshall Islands", "MH"],
["Martinique", "MQ"],
["Mauritania", "MR"],
["Mauritius", "MU"],
["Mayotte", "YT"],
["Mexico", "MX"],
["Micronesia (Federated States of)", "FM"],
["Moldova (Republic of)", "MD"],
["Monaco", "MC"],
["Mongolia", "MN"],
["Montenegro", "ME"],
["Montserrat", "MS"],
["Morocco", "MA"],
["Mozambique", "MZ"],
["Myanmar", "MM"],
["Namibia", "NA"],
["Nauru", "NR"],
["Nepal", "NP"],
["Netherlands", "NL"],
["New Caledonia", "NC"],
["New Zealand", "NZ"],
["Nicaragua", "NI"],
["Niger", "NE"],
["Nigeria", "NG"],
["Niue", "NU"],
["Norfolk Island", "NF"],
["Northern Mariana Islands", "MP"],
["Norway", "NO"],
["Oman", "OM"],
["Pakistan", "PK"],
["Palau", "PW"],
["Palestine", "State of", "PS"],
["Panama", "PA"],
["Papua New Guinea", "PG"],
["Paraguay", "PY"],
["Peru", "PE"],
["Philippines", "PH"],
["Pitcairn", "PN"],
["Poland", "PL"],
["Portugal", "PT"],
["Puerto Rico", "PR"],
["Qatar", "QA"],
["Réunion", "RE"],
["Romania", "RO"],
["Russian Federation", "RU"],
["Rwanda", "RW"],
["Saint Barthélemy", "BL"],
["Saint Helena", "Ascension and Tristan da Cunha", "SH"],
["Saint Kitts and Nevis", "KN"],
["Saint Lucia", "LC"],
["Saint Martin (French part)", "MF"],
["Saint Pierre and Miquelon", "PM"],
["Saint Vincent and the Grenadines", "VC"],
["Samoa", "WS"],
["San Marino", "SM"],
["Sao Tome and Principe", "ST"],
["Saudi Arabia", "SA"],
["Senegal", "SN"],
["Serbia", "RS"],
["Seychelles", "SC"],
["Sierra Leone", "SL"],
["Singapore", "SG"],
["Sint Maarten (Dutch part)", "SX"],
["Slovakia", "SK"],
["Slovenia", "SI"],
["Solomon Islands", "SB"],
["Somalia", "SO"],
["South Africa", "ZA"],
["South Georgia and the South Sandwich Islands", "GS"],
["South Sudan", "SS"],
["Spain", "ES"],
["Sri Lanka", "LK"],
["Sudan", "SD"],
["Suriname", "SR"],
["Svalbard and Jan Mayen", "SJ"],
["Swaziland", "SZ"],
["Sweden", "SE"],
["Switzerland", "CH"],
["Syrian Arab Republic", "SY"],
["Taiwan", "Province of China", "TW"],
["Tajikistan", "TJ"],
["Tanzania", "United Republic of", "TZ"],
["Thailand", "TH"],
["Timor-Leste", "TL"],
["Togo", "TG"],
["Tokelau", "TK"],
["Tonga", "TO"],
["Trinidad and Tobago", "TT"],
["Tunisia", "TN"],
["Turkey", "TR"],
["Turkmenistan", "TM"],
["Turks and Caicos Islands", "TC"],
["Tuvalu", "TV"],
["Uganda", "UG"],
["Ukraine", "UA"],
["United Arab Emirates", "AE"],
["United Kingdom of Great Britain and Northern Ireland", "GB"],
["United States of America", "US"],
["United States Minor Outlying Islands", "UM"],
["Uruguay", "UY"],
["Uzbekistan", "UZ"],
["Vanuatu", "VU"],
["Venezuela (Bolivarian Republic of)", "VE"],
["Viet Nam", "VN"],
["Virgin Islands (British)", "VG"],
["Virgin Islands (U.S.)", "VI"],
["Wallis and Futuna", "WF"],
["Western Sahara", "EH"],
["Yemen", "YE"],
["Zambia", "ZM"],
["Zimbabwe", "ZW"],
];

var CONTINENTS = [
["A1", "--"],
["A2", "--"],
["AD", "EU"],
["AE", "AS"],
["AF", "AS"],
["AG", "NA"],
["AI", "NA"],
["AL", "EU"],
["AM", "AS"],
["AN", "NA"],
["AO", "AF"],
["AP", "AS"],
["AQ", "AN"],
["AR", "SA"],
["AS", "OC"],
["AT", "EU"],
["AU", "OC"],
["AW", "NA"],
["AX", "EU"],
["AZ", "AS"],
["BA", "EU"],
["BB", "NA"],
["BD", "AS"],
["BE", "EU"],
["BF", "AF"],
["BG", "EU"],
["BH", "AS"],
["BI", "AF"],
["BJ", "AF"],
["BL", "NA"],
["BM", "NA"],
["BN", "AS"],
["BO", "SA"],
["BR", "SA"],
["BS", "NA"],
["BT", "AS"],
["BV", "AN"],
["BW", "AF"],
["BY", "EU"],
["BZ", "NA"],
["CA", "NA"],
["CC", "AS"],
["CD", "AF"],
["CF", "AF"],
["CG", "AF"],
["CH", "EU"],
["CI", "AF"],
["CK", "OC"],
["CL", "SA"],
["CM", "AF"],
["CN", "AS"],
["CO", "SA"],
["CR", "NA"],
["CU", "NA"],
["CV", "AF"],
["CX", "AS"],
["CY", "AS"],
["CZ", "EU"],
["DE", "EU"],
["DJ", "AF"],
["DK", "EU"],
["DM", "NA"],
["DO", "NA"],
["DZ", "AF"],
["EC", "SA"],
["EE", "EU"],
["EG", "AF"],
["EH", "AF"],
["ER", "AF"],
["ES", "EU"],
["ET", "AF"],
["EU", "EU"],
["FI", "EU"],
["FJ", "OC"],
["FK", "SA"],
["FM", "OC"],
["FO", "EU"],
["FR", "EU"],
["FX", "EU"],
["GA", "AF"],
["GB", "EU"],
["GD", "NA"],
["GE", "AS"],
["GF", "SA"],
["GG", "EU"],
["GH", "AF"],
["GI", "EU"],
["GL", "NA"],
["GM", "AF"],
["GN", "AF"],
["GP", "NA"],
["GQ", "AF"],
["GR", "EU"],
["GS", "AN"],
["GT", "NA"],
["GU", "OC"],
["GW", "AF"],
["GY", "SA"],
["HK", "AS"],
["HM", "AN"],
["HN", "NA"],
["HR", "EU"],
["HT", "NA"],
["HU", "EU"],
["ID", "AS"],
["IE", "EU"],
["IL", "AS"],
["IM", "EU"],
["IN", "AS"],
["IO", "AS"],
["IQ", "AS"],
["IR", "AS"],
["IS", "EU"],
["IT", "EU"],
["JE", "EU"],
["JM", "NA"],
["JO", "AS"],
["JP", "AS"],
["KE", "AF"],
["KG", "AS"],
["KH", "AS"],
["KI", "OC"],
["KM", "AF"],
["KN", "NA"],
["KP", "AS"],
["KR", "AS"],
["KW", "AS"],
["KY", "NA"],
["KZ", "AS"],
["LA", "AS"],
["LB", "AS"],
["LC", "NA"],
["LI", "EU"],
["LK", "AS"],
["LR", "AF"],
["LS", "AF"],
["LT", "EU"],
["LU", "EU"],
["LV", "EU"],
["LY", "AF"],
["MA", "AF"],
["MC", "EU"],
["MD", "EU"],
["ME", "EU"],
["MF", "NA"],
["MG", "AF"],
["MH", "OC"],
["MK", "EU"],
["ML", "AF"],
["MM", "AS"],
["MN", "AS"],
["MO", "AS"],
["MP", "OC"],
["MQ", "NA"],
["MR", "AF"],
["MS", "NA"],
["MT", "EU"],
["MU", "AF"],
["MV", "AS"],
["MW", "AF"],
["MX", "NA"],
["MY", "AS"],
["MZ", "AF"],
["NA", "AF"],
["NC", "OC"],
["NE", "AF"],
["NF", "OC"],
["NG", "AF"],
["NI", "NA"],
["NL", "EU"],
["NO", "EU"],
["NP", "AS"],
["NR", "OC"],
["NU", "OC"],
["NZ", "OC"],
["O1", "--"],
["OM", "AS"],
["PA", "NA"],
["PE", "SA"],
["PF", "OC"],
["PG", "OC"],
["PH", "AS"],
["PK", "AS"],
["PL", "EU"],
["PM", "NA"],
["PN", "OC"],
["PR", "NA"],
["PS", "AS"],
["PT", "EU"],
["PW", "OC"],
["PY", "SA"],
["QA", "AS"],
["RE", "AF"],
["RO", "EU"],
["RS", "EU"],
["RU", "EU"],
["RW", "AF"],
["SA", "AS"],
["SB", "OC"],
["SC", "AF"],
["SD", "AF"],
["SE", "EU"],
["SG", "AS"],
["SH", "AF"],
["SI", "EU"],
["SJ", "EU"],
["SK", "EU"],
["SL", "AF"],
["SM", "EU"],
["SN", "AF"],
["SO", "AF"],
["SR", "SA"],
["ST", "AF"],
["SV", "NA"],
["SY", "AS"],
["SZ", "AF"],
["TC", "NA"],
["TD", "AF"],
["TF", "AN"],
["TG", "AF"],
["TH", "AS"],
["TJ", "AS"],
["TK", "OC"],
["TL", "AS"],
["TM", "AS"],
["TN", "AF"],
["TO", "OC"],
["TR", "EU"],
["TT", "NA"],
["TV", "OC"],
["TW", "AS"],
["TZ", "AF"],
["UA", "EU"],
["UG", "AF"],
["UM", "OC"],
["US", "NA"],
["UY", "SA"],
["UZ", "AS"],
["VA", "EU"],
["VC", "NA"],
["VE", "SA"],
["VG", "NA"],
["VI", "NA"],
["VN", "AS"],
["VU", "OC"],
["WF", "OC"],
["WS", "OC"],
["YE", "AS"],
["YT", "AF"],
["ZA", "AF"],
["ZM", "AF"],
["ZW", "AF"],
];